#!/usr/bin/env bash
set -euo pipefail

ROOTFS="${1:-}"
if [[ -z "$ROOTFS" ]]; then
  echo "Usage: $0 /path/to/rootfs"
  exit 1
fi

mkdir -p "$ROOTFS"/{bin,boot,dev,etc,home,lib,lib64,media,mnt,opt,proc,root,run,sbin,srv,sys,tmp,usr,var}
mkdir -p "$ROOTFS"/usr/{bin,lib,sbin,share,src}
mkdir -p "$ROOTFS"/var/{log,lib/mkpkg,cache/mkpkg}
mkdir -p "$ROOTFS"/etc/mkpkg
mkdir -p "$ROOTFS"/etc/init.d
mkdir -p "$ROOTFS"/home/maxis

# Basic config placeholders
cat > "$ROOTFS"/etc/hostname <<'EOC'
maxisos
EOC

cat > "$ROOTFS"/etc/locale.conf <<'EOC'
LANG=en_US.UTF-8
EOC

cat > "$ROOTFS"/etc/timezone <<'EOC'
UTC
EOC

cat > "$ROOTFS"/etc/profile <<'EOC'
export LANG=en_US.UTF-8
export PS1="maxis@maxisos:\\w\\$ "
EOC

cat > "$ROOTFS"/etc/mkpkg/repos.conf <<'EOC'
# One repo path per line
/repo/core
/repo/extra
/repo/community
EOC

cat > "$ROOTFS"/etc/passwd <<'EOC'
root:x:0:0:root:/root:/bin/bash
maxis:x:1000:1000:MaxisOS User:/home/maxis:/bin/bash
EOC

cat > "$ROOTFS"/etc/group <<'EOC'
root:x:0:
wheel:x:10:maxis
users:x:1000:maxis
EOC

cat > "$ROOTFS"/etc/shadow <<'EOC'
root:!:19000:0:99999:7:::
maxis:!:19000:0:99999:7:::
EOC

cat > "$ROOTFS"/etc/sudoers <<'EOC'
root ALL=(ALL) ALL
%wheel ALL=(ALL) ALL
EOC

cat > "$ROOTFS"/etc/fstab <<'EOC'
# <fs> <mountpoint> <type> <opts> <dump> <pass>
EOC

cat > "$ROOTFS"/etc/hosts <<'EOC'
127.0.0.1 localhost
::1 localhost
127.0.1.1 maxisos.localdomain maxisos
EOC

cat > "$ROOTFS"/etc/resolv.conf <<'EOC'
# Generated by installer or network manager
nameserver 1.1.1.1
nameserver 8.8.8.8
EOC

cat > "$ROOTFS"/etc/init.d/mountfs <<'EOC'
#!/bin/sh
mount -a
EOC

cat > "$ROOTFS"/etc/init.d/network <<'EOC'
#!/bin/sh
echo "Starting network (placeholder)"
EOC

cat > "$ROOTFS"/etc/init.d/logging <<'EOC'
#!/bin/sh
echo "Starting logging (placeholder)"
EOC

chmod +x "$ROOTFS"/etc/init.d/mountfs
chmod +x "$ROOTFS"/etc/init.d/network
chmod +x "$ROOTFS"/etc/init.d/logging

touch "$ROOTFS"/var/log/messages
touch "$ROOTFS"/var/log/dmesg

chmod 700 "$ROOTFS"/root
chmod 1777 "$ROOTFS"/tmp

echo "Rootfs prepared at $ROOTFS"
